title: Patricio Javier Leonardi
author: Patricio Javier Leonardi
email: patricioleonardi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple first project for gitpages

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  PatricioLeonardi94 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
